### ISSUE TITLE
Pluralization

### ISSUE THREAD

**Issue by andrei4002** [zenangst/NSString-ZENInflections#1]
Hi
Awesome library!
Any chance you'll be adding string pluralization to it?

**Comment by zenangst** [comment]
Haven't given any thought to it but I like the idea!

**Comment by zenangst** [comment]
I've started on this feature, stay tuned

**Comment by zenangst** [comment]
I re-evaluated this, I don't really see the use-case. Feel free to do a pull request with a detailed description if you still think this is needed.
